source 'https://rubygems.org'
gem 'pygments.rb', group: :jekyll_plugins
gem 'kramdown', group: :jekyll_plugins
gem 'rouge', group: :jekyll_plugins
gem 'liquid_reading_time', group: :jekyll_plugins
gem 'jekyll', group: :jekyll_plugins
gem 'jekyll-paginate', group: :jekyll_plugins
gem 'jekyll-watch', group: :jekyll_plugins
gem 'jekyll-sitemap', group: :jekyll_plugins
gem 'jekyll-seo-tag', group: :jekyll_plugins
gem 'jekyll-seo', group: :jekyll_plugins
gem 'jekyll-assets', group: :jekyll_plugins
gem 'jekyll-scholar', group: :jekyll_plugins
