source 'https://rubygems.org'
gem 'pygments.rb', group: :jekyll_plugins
gem 'jekyll-paginate', group: :jekyll_plugins
gem 'jekyll-watch', group: :jekyll_plugins
gem 'kramdown', group: :jekyll_plugins
gem 'jekyll-sitemap', group: :jekyll_plugins
